run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/alfariiizi/vandor-cli
  govet:
    shadow: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    require-explanation: false
    require-specific: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - nolintlint
    - gocritic
    - revive

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # Ignore long lines in generated files
    - path: internal/generators/
      linters:
        - lll
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0